import 'package:flutter/material.dart';
import 'package:flutterapp/car_rentapp/generatedsignupdarkwidget1/generated/GeneratedRectangle2489Widget6.dart';
import 'package:flutterapp/car_rentapp/generatedsignupdarkwidget1/generated/GeneratedStatusBariPhone1313ProWidget11.dart';
import 'package:flutterapp/car_rentapp/generatedsignupdarkwidget1/generated/GeneratedSignupWidget2.dart';
import 'package:flutterapp/car_rentapp/generatedsignupdarkwidget1/generated/GeneratedContinueWidget2.dart';
import 'package:flutterapp/car_rentapp/generatedsignupdarkwidget1/generated/GeneratedHomeIndicatorWidget9.dart';
import 'package:flutterapp/car_rentapp/generatedsignupdarkwidget1/generated/GeneratedGroup7335Widget2.dart';
import 'package:flutterapp/car_rentapp/generatedsignupdarkwidget1/generated/GeneratedRectangle2490Widget4.dart';
import 'package:flutterapp/car_rentapp/generatedsignupdarkwidget1/generated/GeneratedRectangle2492Widget4.dart';
import 'package:flutterapp/car_rentapp/generatedsignupdarkwidget1/generated/GeneratedLastNameWidget2.dart';
import 'package:flutterapp/car_rentapp/generatedsignupdarkwidget1/generated/GeneratedRectangle2491Widget4.dart';
import 'package:flutterapp/car_rentapp/generatedsignupdarkwidget1/generated/GeneratedRectangle2480Widget2.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/car_rentapp/generatedsignupdarkwidget1/generated/GeneratedGroup7275Widget2.dart';
import 'package:flutterapp/car_rentapp/generatedsignupdarkwidget1/generated/GeneratedGridWidget11.dart';
import 'package:flutterapp/car_rentapp/generatedsignupdarkwidget1/generated/GeneratedFirtNameWidget2.dart';
import 'package:flutterapp/car_rentapp/generatedsignupdarkwidget1/generated/GeneratedRectangle2487Widget2.dart';
import 'package:flutterapp/car_rentapp/generatedsignupdarkwidget1/generated/GeneratedPhoneNumberWidget2.dart';
import 'package:flutterapp/car_rentapp/generatedsignupdarkwidget1/generated/GeneratedPasswordWidget2.dart';

/* Frame Sign Up  / Dark
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSignUpDarkWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 22, 22, 26),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 0.0,
                height: 0.0,
                child: GeneratedGridWidget11(),
              ),
              Positioned(
                left: 139.0,
                top: 68.0,
                right: null,
                bottom: null,
                width: 99.0,
                height: 36.0,
                child: GeneratedSignupWidget2(),
              ),
              Positioned(
                left: 20.0,
                top: 578.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 50.0,
                child: GeneratedRectangle2480Widget2(),
              ),
              Positioned(
                left: 20.0,
                top: 175.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 50.0,
                child: GeneratedRectangle2489Widget6(),
              ),
              Positioned(
                left: 158.0,
                top: 595.0,
                right: null,
                bottom: null,
                width: 65.0,
                height: 22.0,
                child: GeneratedContinueWidget2(),
              ),
              Positioned(
                left: 20.0,
                top: 148.0,
                right: null,
                bottom: null,
                width: 66.0,
                height: 19.0,
                child: GeneratedFirtNameWidget2(),
              ),
              Positioned(
                left: 20.0,
                top: 276.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 50.0,
                child: GeneratedRectangle2487Widget2(),
              ),
              Positioned(
                left: 20.0,
                top: 249.0,
                right: null,
                bottom: null,
                width: 72.0,
                height: 19.0,
                child: GeneratedLastNameWidget2(),
              ),
              Positioned(
                left: 106.0,
                top: 377.0,
                right: null,
                bottom: null,
                width: 249.0,
                height: 50.0,
                child: GeneratedRectangle2490Widget4(),
              ),
              Positioned(
                left: 20.0,
                top: 377.0,
                right: null,
                bottom: null,
                width: 76.0,
                height: 50.0,
                child: GeneratedRectangle2492Widget4(),
              ),
              Positioned(
                left: 20.0,
                top: 350.0,
                right: null,
                bottom: null,
                width: 99.0,
                height: 19.0,
                child: GeneratedPhoneNumberWidget2(),
              ),
              Positioned(
                left: 20.0,
                top: 478.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 50.0,
                child: GeneratedRectangle2491Widget4(),
              ),
              Positioned(
                left: 20.0,
                top: 451.0,
                right: null,
                bottom: null,
                width: 69.0,
                height: 22.0,
                child: GeneratedPasswordWidget2(),
              ),
              Positioned(
                left: 76.0,
                top: 652.0,
                right: null,
                bottom: null,
                width: 222.0,
                height: 17.0,
                child: GeneratedGroup7275Widget2(),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: 8.0,
                width: 134.0,
                height: 5.0,
                child: TransformHelper.translate(
                    x: 0.50,
                    y: 0.00,
                    z: 0,
                    child: GeneratedHomeIndicatorWidget9()),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedStatusBariPhone1313ProWidget11(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.042666666666666665;

                  final double height =
                      constraints.maxHeight * 0.014330497516199874;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.8533333333333334,
                        y: constraints.maxHeight * 0.6120689655172413,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup7335Widget2(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
