import 'package:flutter/material.dart';
import 'package:flutterapp/car_rentapp/generatedverifysignup2widget/generated/GeneratedGridWidget10.dart';
import 'package:flutterapp/car_rentapp/generatedverifysignup2widget/generated/GeneratedWesentonurphonea4digitverificationcodeWidget1.dart';
import 'package:flutterapp/car_rentapp/generatedverifysignup2widget/generated/GeneratedRectangle2490Widget3.dart';
import 'package:flutterapp/car_rentapp/generatedverifysignup2widget/generated/GeneratedRectangle2492Widget3.dart';
import 'package:flutterapp/car_rentapp/generatedverifysignup2widget/generated/GeneratedVerifyWidget1.dart';
import 'package:flutterapp/car_rentapp/generatedverifysignup2widget/generated/GeneratedResendcodeWidget1.dart';
import 'package:flutterapp/car_rentapp/generatedverifysignup2widget/generated/GeneratedRectangle2489Widget4.dart';
import 'package:flutterapp/car_rentapp/generatedverifysignup2widget/generated/GeneratedVerifyphonenumberWidget1.dart';
import 'package:flutterapp/car_rentapp/generatedverifysignup2widget/generated/GeneratedRectangle2489Widget5.dart';
import 'package:flutterapp/car_rentapp/generatedverifysignup2widget/generated/GeneratedRectangle2491Widget3.dart';
import 'package:flutterapp/car_rentapp/generatedverifysignup2widget/generated/GeneratedStatusBariPhone1313ProWidget10.dart';
import 'package:flutterapp/car_rentapp/generatedverifysignup2widget/generated/GeneratedNumericKeyboardWidget1.dart';

/* Frame Verify / Sign Up #2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVerifySignUp2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 0.0,
                height: 0.0,
                child: GeneratedGridWidget10(),
              ),
              Positioned(
                left: 52.0,
                top: 68.0,
                right: null,
                bottom: null,
                width: 273.0,
                height: 36.0,
                child: GeneratedVerifyphonenumberWidget1(),
              ),
              Positioned(
                left: 36.0,
                top: 112.0,
                right: null,
                bottom: null,
                width: 304.0,
                height: 19.0,
                child: GeneratedWesentonurphonea4digitverificationcodeWidget1(),
              ),
              Positioned(
                left: 20.0,
                top: 175.0,
                right: null,
                bottom: null,
                width: 76.0,
                height: 50.0,
                child: GeneratedRectangle2489Widget4(),
              ),
              Positioned(
                left: 106.0,
                top: 175.0,
                right: null,
                bottom: null,
                width: 77.0,
                height: 50.0,
                child: GeneratedRectangle2490Widget3(),
              ),
              Positioned(
                left: 193.0,
                top: 175.0,
                right: null,
                bottom: null,
                width: 77.0,
                height: 50.0,
                child: GeneratedRectangle2491Widget3(),
              ),
              Positioned(
                left: 280.0,
                top: 175.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 50.0,
                child: GeneratedRectangle2492Widget3(),
              ),
              Positioned(
                left: 20.0,
                top: 447.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 50.0,
                child: GeneratedRectangle2489Widget5(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedStatusBariPhone1313ProWidget10(),
              ),
              Positioned(
                left: 142.0,
                top: 249.0,
                right: null,
                bottom: null,
                width: 93.0,
                height: 19.0,
                child: GeneratedResendcodeWidget1(),
              ),
              Positioned(
                left: 168.0,
                top: 464.0,
                right: null,
                bottom: null,
                width: 44.0,
                height: 22.0,
                child: GeneratedVerifyWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 521.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 291.0,
                child: GeneratedNumericKeyboardWidget1(),
              )
            ]),
      ),
    ));
  }
}
