import 'package:flutter/material.dart';
import 'package:flutterapp/car_rentapp/generatedwidget3/generated/GeneratedGridWidget6.dart';
import 'package:flutterapp/car_rentapp/generatedwidget3/generated/GeneratedStatusBariPhone1313ProWidget6.dart';
import 'package:flutterapp/car_rentapp/generatedwidget3/generated/GeneratedDBWidget.dart';

/* Frame ПРОФИЛЬ
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 22, 22, 26),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 0.0,
                height: 0.0,
                child: GeneratedGridWidget6(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedStatusBariPhone1313ProWidget6(),
              ),
              Positioned(
                left: 27.0,
                top: 310.0,
                right: null,
                bottom: null,
                width: 329.0,
                height: 193.0,
                child: GeneratedDBWidget(),
              )
            ]),
      ),
    ));
  }
}
