import 'package:flutter/material.dart';
import 'package:flutterapp/car_rentapp/generatedverifysignup2darkwidget/generated/GeneratedRectangle2489Widget2.dart';
import 'package:flutterapp/car_rentapp/generatedverifysignup2darkwidget/generated/GeneratedStatusBariPhone1313ProWidget4.dart';
import 'package:flutterapp/car_rentapp/generatedverifysignup2darkwidget/generated/GeneratedWesentonurphonea4digitverificationcodeWidget.dart';
import 'package:flutterapp/car_rentapp/generatedverifysignup2darkwidget/generated/GeneratedResendcodeWidget.dart';
import 'package:flutterapp/car_rentapp/generatedverifysignup2darkwidget/generated/GeneratedGridWidget4.dart';
import 'package:flutterapp/car_rentapp/generatedverifysignup2darkwidget/generated/GeneratedRectangle2492Widget1.dart';
import 'package:flutterapp/car_rentapp/generatedverifysignup2darkwidget/generated/GeneratedVerifyWidget.dart';
import 'package:flutterapp/car_rentapp/generatedverifysignup2darkwidget/generated/GeneratedRectangle2489Widget1.dart';
import 'package:flutterapp/car_rentapp/generatedverifysignup2darkwidget/generated/GeneratedRectangle2490Widget1.dart';
import 'package:flutterapp/car_rentapp/generatedverifysignup2darkwidget/generated/GeneratedNumericKeyboardWidget.dart';
import 'package:flutterapp/car_rentapp/generatedverifysignup2darkwidget/generated/GeneratedRectangle2491Widget1.dart';
import 'package:flutterapp/car_rentapp/generatedverifysignup2darkwidget/generated/GeneratedVerifyphonenumberWidget.dart';

/* Frame Verify / Sign Up #2  / Dark
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVerifySignUp2DarkWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 22, 22, 26),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 0.0,
                height: 0.0,
                child: GeneratedGridWidget4(),
              ),
              Positioned(
                left: 52.0,
                top: 68.0,
                right: null,
                bottom: null,
                width: 273.0,
                height: 36.0,
                child: GeneratedVerifyphonenumberWidget(),
              ),
              Positioned(
                left: 36.0,
                top: 112.0,
                right: null,
                bottom: null,
                width: 304.0,
                height: 19.0,
                child: GeneratedWesentonurphonea4digitverificationcodeWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 175.0,
                right: null,
                bottom: null,
                width: 76.0,
                height: 50.0,
                child: GeneratedRectangle2489Widget1(),
              ),
              Positioned(
                left: 106.0,
                top: 175.0,
                right: null,
                bottom: null,
                width: 77.0,
                height: 50.0,
                child: GeneratedRectangle2490Widget1(),
              ),
              Positioned(
                left: 193.0,
                top: 175.0,
                right: null,
                bottom: null,
                width: 77.0,
                height: 50.0,
                child: GeneratedRectangle2491Widget1(),
              ),
              Positioned(
                left: 280.0,
                top: 175.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 50.0,
                child: GeneratedRectangle2492Widget1(),
              ),
              Positioned(
                left: 20.0,
                top: 447.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 50.0,
                child: GeneratedRectangle2489Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedStatusBariPhone1313ProWidget4(),
              ),
              Positioned(
                left: 142.0,
                top: 249.0,
                right: null,
                bottom: null,
                width: 93.0,
                height: 19.0,
                child: GeneratedResendcodeWidget(),
              ),
              Positioned(
                left: 168.0,
                top: 464.0,
                right: null,
                bottom: null,
                width: 44.0,
                height: 22.0,
                child: GeneratedVerifyWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 521.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 291.0,
                child: GeneratedNumericKeyboardWidget(),
              )
            ]),
      ),
    ));
  }
}
