import 'package:flutter/material.dart';
import 'package:flutterapp/car_rentapp/generatedwidget6/generated/GeneratedDBWidget1.dart';
import 'package:flutterapp/car_rentapp/generatedwidget6/generated/GeneratedStatusBariPhone1313ProWidget8.dart';
import 'package:flutterapp/car_rentapp/generatedwidget6/generated/GeneratedGridWidget8.dart';

/* Frame История
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWidget6 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 22, 22, 26),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 0.0,
                height: 0.0,
                child: GeneratedGridWidget8(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedStatusBariPhone1313ProWidget8(),
              ),
              Positioned(
                left: 47.0,
                top: 344.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 159.0,
                child: GeneratedDBWidget1(),
              )
            ]),
      ),
    ));
  }
}
