import 'package:flutter/material.dart';
import 'package:flutterapp/car_rentapp/generatedsignupdarkwidget/generated/GeneratedFirtNameWidget.dart';
import 'package:flutterapp/car_rentapp/generatedsignupdarkwidget/generated/GeneratedContinueWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/car_rentapp/generatedsignupdarkwidget/generated/GeneratedSignupWidget.dart';
import 'package:flutterapp/car_rentapp/generatedsignupdarkwidget/generated/GeneratedRectangle2480Widget.dart';
import 'package:flutterapp/car_rentapp/generatedsignupdarkwidget/generated/GeneratedRectangle2492Widget.dart';
import 'package:flutterapp/car_rentapp/generatedsignupdarkwidget/generated/GeneratedRectangle2487Widget.dart';
import 'package:flutterapp/car_rentapp/generatedsignupdarkwidget/generated/GeneratedLastNameWidget.dart';
import 'package:flutterapp/car_rentapp/generatedsignupdarkwidget/generated/GeneratedRectangle2489Widget.dart';
import 'package:flutterapp/car_rentapp/generatedsignupdarkwidget/generated/GeneratedRectangle2491Widget.dart';
import 'package:flutterapp/car_rentapp/generatedsignupdarkwidget/generated/GeneratedPasswordWidget.dart';
import 'package:flutterapp/car_rentapp/generatedsignupdarkwidget/generated/GeneratedStatusBariPhone1313ProWidget3.dart';
import 'package:flutterapp/car_rentapp/generatedsignupdarkwidget/generated/GeneratedGridWidget3.dart';
import 'package:flutterapp/car_rentapp/generatedsignupdarkwidget/generated/GeneratedPhoneNumberWidget.dart';
import 'package:flutterapp/car_rentapp/generatedsignupdarkwidget/generated/GeneratedGroup7275Widget.dart';
import 'package:flutterapp/car_rentapp/generatedsignupdarkwidget/generated/GeneratedGroup7335Widget.dart';
import 'package:flutterapp/car_rentapp/generatedsignupdarkwidget/generated/GeneratedRectangle2490Widget.dart';
import 'package:flutterapp/car_rentapp/generatedsignupdarkwidget/generated/GeneratedHomeIndicatorWidget3.dart';

/* Frame Sign Up  / Dark
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSignUpDarkWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 22, 22, 26),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 0.0,
                height: 0.0,
                child: GeneratedGridWidget3(),
              ),
              Positioned(
                left: 139.0,
                top: 68.0,
                right: null,
                bottom: null,
                width: 99.0,
                height: 36.0,
                child: GeneratedSignupWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 578.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 50.0,
                child: GeneratedRectangle2480Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 175.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 50.0,
                child: GeneratedRectangle2489Widget(),
              ),
              Positioned(
                left: 158.0,
                top: 595.0,
                right: null,
                bottom: null,
                width: 65.0,
                height: 22.0,
                child: GeneratedContinueWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 148.0,
                right: null,
                bottom: null,
                width: 66.0,
                height: 19.0,
                child: GeneratedFirtNameWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 276.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 50.0,
                child: GeneratedRectangle2487Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 249.0,
                right: null,
                bottom: null,
                width: 72.0,
                height: 19.0,
                child: GeneratedLastNameWidget(),
              ),
              Positioned(
                left: 106.0,
                top: 377.0,
                right: null,
                bottom: null,
                width: 249.0,
                height: 50.0,
                child: GeneratedRectangle2490Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 377.0,
                right: null,
                bottom: null,
                width: 76.0,
                height: 50.0,
                child: GeneratedRectangle2492Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 350.0,
                right: null,
                bottom: null,
                width: 99.0,
                height: 19.0,
                child: GeneratedPhoneNumberWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 478.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 50.0,
                child: GeneratedRectangle2491Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 451.0,
                right: null,
                bottom: null,
                width: 69.0,
                height: 22.0,
                child: GeneratedPasswordWidget(),
              ),
              Positioned(
                left: 76.0,
                top: 652.0,
                right: null,
                bottom: null,
                width: 222.0,
                height: 17.0,
                child: GeneratedGroup7275Widget(),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: 8.0,
                width: 134.0,
                height: 5.0,
                child: TransformHelper.translate(
                    x: 0.50,
                    y: 0.00,
                    z: 0,
                    child: GeneratedHomeIndicatorWidget3()),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedStatusBariPhone1313ProWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.042666666666666665;

                  final double height =
                      constraints.maxHeight * 0.014330497516199874;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.8533333333333334,
                        y: constraints.maxHeight * 0.6120689655172413,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup7335Widget(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
