import 'package:flutter/material.dart';
import 'package:flutterapp/car_rentapp/generatedsignupwidget/generated/GeneratedRectangle2491Widget2.dart';
import 'package:flutterapp/car_rentapp/generatedsignupwidget/generated/GeneratedRectangle2480Widget1.dart';
import 'package:flutterapp/car_rentapp/generatedsignupwidget/generated/GeneratedHomeIndicatorWidget6.dart';
import 'package:flutterapp/car_rentapp/generatedsignupwidget/generated/GeneratedGroup7335Widget1.dart';
import 'package:flutterapp/car_rentapp/generatedsignupwidget/generated/GeneratedContinueWidget1.dart';
import 'package:flutterapp/car_rentapp/generatedsignupwidget/generated/GeneratedFirtNameWidget1.dart';
import 'package:flutterapp/car_rentapp/generatedsignupwidget/generated/GeneratedRectangle2487Widget1.dart';
import 'package:flutterapp/car_rentapp/generatedsignupwidget/generated/GeneratedRectangle2490Widget2.dart';
import 'package:flutterapp/car_rentapp/generatedsignupwidget/generated/GeneratedPhoneNumberWidget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/car_rentapp/generatedsignupwidget/generated/GeneratedSignupWidget1.dart';
import 'package:flutterapp/car_rentapp/generatedsignupwidget/generated/GeneratedGridWidget9.dart';
import 'package:flutterapp/car_rentapp/generatedsignupwidget/generated/GeneratedRectangle2492Widget2.dart';
import 'package:flutterapp/car_rentapp/generatedsignupwidget/generated/GeneratedLastNameWidget1.dart';
import 'package:flutterapp/car_rentapp/generatedsignupwidget/generated/GeneratedPasswordWidget1.dart';
import 'package:flutterapp/car_rentapp/generatedsignupwidget/generated/GeneratedRectangle2489Widget3.dart';
import 'package:flutterapp/car_rentapp/generatedsignupwidget/generated/GeneratedStatusBariPhone1313ProWidget9.dart';
import 'package:flutterapp/car_rentapp/generatedsignupwidget/generated/GeneratedGroup7275Widget1.dart';

/* Frame Sign Up
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSignUpWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 0.0,
                height: 0.0,
                child: GeneratedGridWidget9(),
              ),
              Positioned(
                left: 139.0,
                top: 68.0,
                right: null,
                bottom: null,
                width: 99.0,
                height: 36.0,
                child: GeneratedSignupWidget1(),
              ),
              Positioned(
                left: 20.0,
                top: 578.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 50.0,
                child: GeneratedRectangle2480Widget1(),
              ),
              Positioned(
                left: 20.0,
                top: 175.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 50.0,
                child: GeneratedRectangle2489Widget3(),
              ),
              Positioned(
                left: 158.0,
                top: 595.0,
                right: null,
                bottom: null,
                width: 65.0,
                height: 22.0,
                child: GeneratedContinueWidget1(),
              ),
              Positioned(
                left: 20.0,
                top: 148.0,
                right: null,
                bottom: null,
                width: 66.0,
                height: 19.0,
                child: GeneratedFirtNameWidget1(),
              ),
              Positioned(
                left: 20.0,
                top: 276.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 50.0,
                child: GeneratedRectangle2487Widget1(),
              ),
              Positioned(
                left: 20.0,
                top: 249.0,
                right: null,
                bottom: null,
                width: 72.0,
                height: 19.0,
                child: GeneratedLastNameWidget1(),
              ),
              Positioned(
                left: 106.0,
                top: 377.0,
                right: null,
                bottom: null,
                width: 249.0,
                height: 50.0,
                child: GeneratedRectangle2490Widget2(),
              ),
              Positioned(
                left: 20.0,
                top: 377.0,
                right: null,
                bottom: null,
                width: 76.0,
                height: 50.0,
                child: GeneratedRectangle2492Widget2(),
              ),
              Positioned(
                left: 20.0,
                top: 350.0,
                right: null,
                bottom: null,
                width: 99.0,
                height: 19.0,
                child: GeneratedPhoneNumberWidget1(),
              ),
              Positioned(
                left: 20.0,
                top: 478.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 50.0,
                child: GeneratedRectangle2491Widget2(),
              ),
              Positioned(
                left: 20.0,
                top: 451.0,
                right: null,
                bottom: null,
                width: 69.0,
                height: 22.0,
                child: GeneratedPasswordWidget1(),
              ),
              Positioned(
                left: 76.0,
                top: 652.0,
                right: null,
                bottom: null,
                width: 222.0,
                height: 17.0,
                child: GeneratedGroup7275Widget1(),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: 8.0,
                width: 134.0,
                height: 5.0,
                child: TransformHelper.translate(
                    x: 0.50,
                    y: 0.00,
                    z: 0,
                    child: GeneratedHomeIndicatorWidget6()),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedStatusBariPhone1313ProWidget9(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.042666666666666665;

                  final double height =
                      constraints.maxHeight * 0.014330497516199874;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.8533333333333334,
                        y: constraints.maxHeight * 0.6120689655172413,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup7335Widget1(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
