import 'package:flutter/material.dart';
import 'package:flutterapp/car_rentapp/generatedhomescreendarkwidget/generated/GeneratedGridWidget.dart';
import 'package:flutterapp/car_rentapp/generatedhomescreendarkwidget/generated/GeneratedGroup7370Widget.dart';
import 'package:flutterapp/car_rentapp/generatedhomescreendarkwidget/generated/GeneratedHomeIndicatorWidget.dart';
import 'package:flutterapp/car_rentapp/generatedhomescreendarkwidget/generated/GeneratedGroup7366Widget.dart';
import 'package:flutterapp/car_rentapp/generatedhomescreendarkwidget/generated/GeneratedSavedWidget.dart';
import 'package:flutterapp/car_rentapp/generatedhomescreendarkwidget/generated/GeneratedGroup7369Widget.dart';
import 'package:flutterapp/car_rentapp/generatedhomescreendarkwidget/generated/GeneratedGroup7366Widget1.dart';
import 'package:flutterapp/car_rentapp/generatedhomescreendarkwidget/generated/GeneratedRectangle2528Widget.dart';
import 'package:flutterapp/car_rentapp/generatedhomescreendarkwidget/generated/GeneratedGroup7406Widget.dart';
import 'package:flutterapp/car_rentapp/generatedhomescreendarkwidget/generated/GeneratedStatusBariPhone1313ProWidget.dart';
import 'package:flutterapp/car_rentapp/generatedhomescreendarkwidget/generated/GeneratedGroup7371Widget.dart';
import 'package:flutterapp/car_rentapp/generatedhomescreendarkwidget/generated/GeneratedGroup7374Widget.dart';
import 'package:flutterapp/car_rentapp/generatedhomescreendarkwidget/generated/GeneratedHistoryWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/car_rentapp/generatedhomescreendarkwidget/generated/GeneratedGroup7368Widget.dart';
import 'package:flutterapp/car_rentapp/generatedhomescreendarkwidget/generated/GeneratedGroup7405Widget.dart';
import 'package:flutterapp/car_rentapp/generatedhomescreendarkwidget/generated/GeneratedProfileWidget.dart';
import 'package:flutterapp/car_rentapp/generatedhomescreendarkwidget/generated/GeneratedDiscoverWidget.dart';

/* Frame Home Screen / Dark
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomeScreenDarkWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 22, 22, 26),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 668.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 257.0,
                child: GeneratedGroup7366Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 0.0,
                height: 0.0,
                child: GeneratedGridWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedStatusBariPhone1313ProWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 64.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 50.0,
                child: GeneratedGroup7374Widget(),
              ),
              Positioned(
                left: 140.0,
                top: 674.0,
                right: null,
                bottom: null,
                width: 94.0,
                height: 46.0,
                child: GeneratedGroup7405Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 730.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 82.0,
                child: GeneratedRectangle2528Widget(),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: 8.0,
                width: 134.0,
                height: 5.0,
                child: TransformHelper.translate(
                    x: 0.50,
                    y: 0.00,
                    z: 0,
                    child: GeneratedHomeIndicatorWidget()),
              ),
              Positioned(
                left: 22.0,
                top: 773.0,
                right: null,
                bottom: null,
                width: 58.0,
                height: 20.0,
                child: GeneratedDiscoverWidget(),
              ),
              Positioned(
                left: 125.0,
                top: 773.0,
                right: null,
                bottom: null,
                width: 49.0,
                height: 20.0,
                child: GeneratedHistoryWidget(),
              ),
              Positioned(
                left: 223.0,
                top: 773.0,
                right: null,
                bottom: null,
                width: 42.0,
                height: 20.0,
                child: GeneratedSavedWidget(),
              ),
              Positioned(
                left: 314.0,
                top: 773.0,
                right: null,
                bottom: null,
                width: 44.0,
                height: 20.0,
                child: GeneratedProfileWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 134.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 257.0,
                child: GeneratedGroup7366Widget1(),
              ),
              Positioned(
                left: 20.0,
                top: 401.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 257.0,
                child: GeneratedGroup7406Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.05333333333333334;

                  final double height =
                      constraints.maxHeight * 0.024630541871921183;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.09866666666666667,
                        y: constraints.maxHeight * 0.9187192118226601,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup7368Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.042666666666666665;

                  final double height =
                      constraints.maxHeight * 0.022167487684729065;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.8666666666666667,
                        y: constraints.maxHeight * 0.9199507389162561,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup7369Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.037333333333333336;

                  final double height =
                      constraints.maxHeight * 0.022167487684729065;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.624,
                        y: constraints.maxHeight * 0.9199507389162561,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup7370Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.05333333333333334;

                  final double height =
                      constraints.maxHeight * 0.024630541871921183;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.36533333333333334,
                        y: constraints.maxHeight * 0.9174876847290641,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup7371Widget(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
