import 'package:flutter/material.dart';
import 'package:flutterapp/car_rentapp/generatediphone13promax2widget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/car_rentapp/generatediphone13promax2widget/generated/GeneratedSkipWidget.dart';
import 'package:flutterapp/car_rentapp/generatediphone13promax2widget/generated/GeneratedEllipse5Widget.dart';
import 'package:flutterapp/car_rentapp/generatediphone13promax2widget/generated/GeneratedEllipse6Widget.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutterapp/car_rentapp/generatediphone13promax2widget/generated/GeneratedDevonjansevanrensburgZTI81GyvVHsunsplashremovebgpreview.dart';
import 'package:flutterapp/car_rentapp/generatediphone13promax2widget/generated/GeneratedCARSKARTWidget.dart';
import 'package:flutterapp/car_rentapp/generatediphone13promax2widget/generated/GeneratedWidget.dart';
import 'package:flutterapp/car_rentapp/generatediphone13promax2widget/generated/GeneratedEllipse1Widget.dart';
import 'package:flutterapp/car_rentapp/generatediphone13promax2widget/generated/GeneratedEllipse8Widget.dart';
import 'package:flutterapp/car_rentapp/generatediphone13promax2widget/generated/GeneratedGOGOWidget.dart';
import 'package:flutterapp/car_rentapp/generatediphone13promax2widget/generated/GeneratedEllipse7Widget.dart';
import 'package:flutterapp/car_rentapp/generatediphone13promax2widget/generated/GeneratedEllipse2Widget.dart';
import 'package:flutterapp/car_rentapp/generatediphone13promax2widget/generated/GeneratedEllipse3Widget.dart';
import 'package:flutterapp/car_rentapp/generatediphone13promax2widget/generated/GeneratedEllipse4Widget.dart';

/* Frame iPhone 13 Pro Max - 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      decoration: BoxDecoration(
        boxShadow: kIsWeb
            ? []
            : [
                BoxShadow(
                  color: Color.fromARGB(63, 0, 0, 0),
                  offset: Offset(7.0, 4.0),
                  blurRadius: 4.0,
                )
              ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(50.0),
        child: LayoutBuilder(
            builder: (BuildContext context, BoxConstraints constraints) {
          return SingleChildScrollView(
            scrollDirection: Axis.horizontal,
            child: Container(
                width: 454.0,
                child: Stack(children: [
                  Container(
                      height: constraints.maxHeight,
                      child: Container(
                        width: 428.0,
                        height: 926.0,
                        decoration: BoxDecoration(
                          borderRadius: BorderRadius.circular(50.0),
                        ),
                        child: Stack(
                            fit: StackFit.expand,
                            alignment: Alignment.center,
                            overflow: Overflow.visible,
                            children: [
                              ClipRRect(
                                borderRadius: BorderRadius.circular(50.0),
                                child: Container(
                                  color: Color.fromARGB(255, 54, 54, 54),
                                ),
                              ),
                              Positioned(
                                left: -32.0,
                                top: 51.0,
                                right: null,
                                bottom: null,
                                width: 486.0,
                                height: 897.0,
                                child:
                                    GeneratedDevonjansevanrensburgZTI81GyvVHsunsplashremovebgpreview(),
                              ),
                              Positioned(
                                left: 189.0,
                                top: 737.0,
                                right: null,
                                bottom: null,
                                width: 10.0,
                                height: 10.0,
                                child: GeneratedEllipse5Widget(),
                              ),
                              Positioned(
                                left: 210.0,
                                top: 737.0,
                                right: null,
                                bottom: null,
                                width: 10.0,
                                height: 10.0,
                                child: GeneratedEllipse6Widget(),
                              ),
                              Positioned(
                                left: 229.0,
                                top: 737.0,
                                right: null,
                                bottom: null,
                                width: 10.0,
                                height: 10.0,
                                child: GeneratedEllipse7Widget(),
                              ),
                              Positioned(
                                left: 247.0,
                                top: 737.0,
                                right: null,
                                bottom: null,
                                width: 10.0,
                                height: 10.0,
                                child: GeneratedEllipse8Widget(),
                              ),
                              Positioned(
                                left: 84.0,
                                top: 820.0,
                                right: null,
                                bottom: null,
                                width: 265.0,
                                height: 61.0,
                                child: GeneratedRectangle1Widget(),
                              ),
                              Positioned(
                                left: 167.0,
                                top: 836.0,
                                right: null,
                                bottom: null,
                                width: 86.0,
                                height: 35.0,
                                child: GeneratedGOGOWidget(),
                              ),
                              Positioned(
                                left: 84.0,
                                top: 211.0,
                                right: null,
                                bottom: null,
                                width: 270.0,
                                height: 61.0,
                                child: GeneratedCARSKARTWidget(),
                              ),
                              Positioned(
                                left: 89.0,
                                top: 279.0,
                                right: null,
                                bottom: null,
                                width: 246.0,
                                height: 44.0,
                                child: GeneratedWidget(),
                              ),
                              Positioned(
                                left: 189.0,
                                top: 737.0,
                                right: null,
                                bottom: null,
                                width: 10.0,
                                height: 10.0,
                                child: GeneratedEllipse1Widget(),
                              ),
                              Positioned(
                                left: 210.0,
                                top: 737.0,
                                right: null,
                                bottom: null,
                                width: 10.0,
                                height: 10.0,
                                child: GeneratedEllipse2Widget(),
                              ),
                              Positioned(
                                left: 229.0,
                                top: 737.0,
                                right: null,
                                bottom: null,
                                width: 10.0,
                                height: 10.0,
                                child: GeneratedEllipse3Widget(),
                              ),
                              Positioned(
                                left: 247.0,
                                top: 737.0,
                                right: null,
                                bottom: null,
                                width: 10.0,
                                height: 10.0,
                                child: GeneratedEllipse4Widget(),
                              ),
                              Positioned(
                                left: 359.0,
                                top: 51.0,
                                right: null,
                                bottom: null,
                                width: 47.0,
                                height: 31.0,
                                child: GeneratedSkipWidget(),
                              )
                            ]),
                      ))
                ])),
          );
        }),
      ),
    ));
  }
}
