import 'package:flutter/material.dart';
import 'package:flutterapp/car_rentapp/generatedwidget1/generated/GeneratedGridWidget5.dart';
import 'package:flutterapp/car_rentapp/generatedwidget1/generated/GeneratedStatusBariPhone1313ProWidget5.dart';
import 'package:flutterapp/car_rentapp/generatedwidget1/generated/GeneratedWidget2.dart';

/* Frame ОПЛАТА
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 22, 22, 26),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 0.0,
                height: 0.0,
                child: GeneratedGridWidget5(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedStatusBariPhone1313ProWidget5(),
              ),
              Positioned(
                left: 43.0,
                top: 307.0,
                right: null,
                bottom: null,
                width: 293.0,
                height: 74.0,
                child: GeneratedWidget2(),
              )
            ]),
      ),
    ));
  }
}
